### ISSUE TITLE
Marking page - faster marking

### ISSUE THREAD

**Issue by davidharrison92** [davidharrison92/sociallydistantpubquiz#10]
It basically groups it per question.

Q1: What color is the Sky?

Blue (76 teams) [tickbox]
Bloooo (1 team) [tickbox]
It's a conspiracy (2 teams) [tickbox]

Then when you hit "yes" it gives a mark to EVERY team with the answer.

**Comment by davidharrison92** [comment]
to do:
- remove team_round_score
- add column for correct answer
- calculate score from submitted_answers table

**Comment by gjfwalker** [comment]
select count(*), answer,question_number from submitted_answers where round_number = 1 group by answer, question_number order by question_number;
