### ISSUE TITLE
Minor - Team Secret to end of page.

### ISSUE THREAD

**Issue by davidharrison92** [davidharrison92/sociallydistantpubquiz#14]
Some teams were hitting enter after putting in their secret.

They would have been able to re-send answers, but it adds confusion.

- Move team secret down by the submit button
- Can this field be set to not allow submit by hitting enter?

**Comment by gjfwalker** [comment]
Yeah you can change the behavior of enter with some jquery
https://stackoverflow.com/questions/18741156/how-to-remove-the-enter-key-functionality
