### ISSUE TITLE
Feature: Team persistence (log in / sessions)

### ISSUE THREAD

**Issue by davidharrison92** [davidharrison92/sociallydistantpubquiz#3]

**Comment by davidharrison92** [comment]
Maybe https://developer.twitter.com/en/docs/basics/authentication/guides/log-in-with-twitter

**Comment by gjfwalker** [comment]
Persistence using $_SESSION is easy and we can do things like keeping track of team name etc with a few extra lines. I wrote a login function also using $_SESSION which isn't attached to a db table yet. (no branch as I don't have permissions)
If we go ahead with login, I think we will still require people to sign up for the next quiz manually, so we know about traffic and which teams to show on the leaderboard.

**Comment by davidharrison92** [comment]
Exactly. Just like a real quiz, when the quiz is over, no data is kept. I empty every database table after every quiz.

$_SESSION might be the answer here. We fall back to Team Name & Secret if no session exists.
